-- Tabela de Configuração do QR Code
CREATE TABLE config (
  id TEXT PRIMARY KEY DEFAULT 'main',
  destination_url TEXT NOT NULL
);

INSERT INTO config (id, destination_url) VALUES ('main', 'https://google.com') ON CONFLICT DO NOTHING;

-- Tabela de Leads do Formulário
CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nome TEXT,
  whatsapp TEXT,
  email TEXT,
  cep TEXT,
  pequenos TEXT,
  fase TEXT,
  escola TEXT,
  relacao TEXT,
  origem TEXT,
  desapego TEXT
);

-- Ative o acesso público (opcional, dependendo da sua segurança)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir inserção pública" ON leads FOR INSERT WITH CHECK (true);
